spring:
  application:
    name: microservice-tests
  datasource:
    url: jdbc:h2:mem:testdb;Mode=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: microservice-tests
